name: Build & Deploy
on:
  push:
    branches:
      - main
  pull_request_review:
    branches:
      - main
jobs:
  deploy:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          submodules: true
          fetch-depth: 0
      - name: Disable quotePath
         run: git config core.quotePath false
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: '0.104.3'
          extended: true
      - name: Build Site
         run: hugo --minify
         run: sed -e 3a\'<script data-host="https://freewebanalytics.net/public" data-dnt="false" src="https://freewebanalytics.net/js/script.js" id="ZwSg9rf6GA" async defer></script>' ./public/*.html
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/
